print("What is your name human? ")
name = input()
print("How old are you?")
age = int(input())
print("How tall are you (in metres)?")
height = float (input())
print("How much do you weight (in kg)?")
weight = float(input())
bmi = weight/height**2
print(name,"you are", age, "years old and you BMI is ", bmi)
print(f"{name} you are {age} years old and you BMI is {bmi:.2f}")
print("{} you are {} years old and you BMI is {:.5f}".format(name, age, bmi))